# Generated by Django 6.0.3 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtask",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Email task",
                "verbose_name_plural": "Email tasks",
            },
        ),
        migrations.AddField(
            model_name="emailtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emailtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("sent", "sent"),
                    ("error", "error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="emailtask",
            index=models.Index(fields=["status"], name="parser_emai_status_8340bb_idx"),
        ),
    ]
